# Generated by Django 5.0.6 on 2024-05-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('CreditScore', models.IntegerField()),
                ('Geography', models.IntegerField()),
                ('Gender', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Tenure', models.IntegerField()),
                ('Balance', models.FloatField()),
                ('NumOfProductsts', models.IntegerField()),
                ('HasCrCard', models.IntegerField()),
                ('IsActiveMember', models.IntegerField()),
                ('EstimatedSalary', models.FloatField()),
                ('searchTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
