# Generated by Django 5.0.6 on 2024-05-23 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchlog',
            old_name='NumOfProductsts',
            new_name='NumOfProducts',
        ),
    ]
